DROP DATABASE IF EXISTS bluemoon_db;
CREATE DATABASE bluemoon_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bluemoon_db;

CREATE TABLE TAI_KHOAN (
    MaTK INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro VARCHAR(20) NOT NULL
);

CREATE TABLE KHOAN_PHI (
    MaKhoanPhi INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoanPhi VARCHAR(100) NOT NULL,
    DonGia DOUBLE DEFAULT 0,
    DonViTinh VARCHAR(20),
    LoaiPhi INT DEFAULT 0,
    TrangThai INT DEFAULT 1
);

CREATE TABLE CAN_HO (
    MaCanHo INT AUTO_INCREMENT PRIMARY KEY,
    SoCanHo VARCHAR(20) NOT NULL UNIQUE,
    DienTich DOUBLE NOT NULL,
    TrangThai INT DEFAULT 0
);

CREATE TABLE HO_KHAU (
    MaHo INT AUTO_INCREMENT PRIMARY KEY,
    SoCanHo VARCHAR(20) NOT NULL,
    TenChuHo VARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    NgayTao DATE DEFAULT (CURRENT_DATE),
    IsDeleted INT DEFAULT 0,
    FOREIGN KEY (SoCanHo) REFERENCES CAN_HO(SoCanHo) ON UPDATE CASCADE
);

CREATE TABLE NHAN_KHAU (
    MaNhanKhau INT AUTO_INCREMENT PRIMARY KEY,
    MaHo INT,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh VARCHAR(10),
    CCCD VARCHAR(20),
    QuanHe VARCHAR(30),
    IsDeleted INT DEFAULT 0,
    FOREIGN KEY (MaHo) REFERENCES HO_KHAU(MaHo)
);

CREATE TABLE TAM_TRU_TAM_VANG (
    MaTTTV INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT NOT NULL,
    LoaiHinh VARCHAR(20) NOT NULL,
    TuNgay DATE NOT NULL,
    DenNgay DATE,
    LyDo TEXT,
    FOREIGN KEY (MaNhanKhau) REFERENCES NHAN_KHAU(MaNhanKhau)
);

CREATE TABLE CONG_NO (
    MaCongNo INT AUTO_INCREMENT PRIMARY KEY,
    MaHo INT NOT NULL,
    MaKhoanPhi INT NOT NULL,
    Thang INT NOT NULL,
    Nam INT NOT NULL,
    SoTienPhaiDong DOUBLE DEFAULT 0,
    SoTienDaDong DOUBLE DEFAULT 0,
    TrangThai INT DEFAULT 0,
    FOREIGN KEY (MaHo) REFERENCES HO_KHAU(MaHo),
    FOREIGN KEY (MaKhoanPhi) REFERENCES KHOAN_PHI(MaKhoanPhi)
);

CREATE TABLE GIAO_DICH_NOP_TIEN (
    MaGiaoDich INT AUTO_INCREMENT PRIMARY KEY,
    MaHo INT NOT NULL,
    MaKhoanPhi INT NOT NULL,
    SoTien DOUBLE NOT NULL,
    NgayNop DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiNop VARCHAR(100),
    GhiChu TEXT,
    FOREIGN KEY (MaHo) REFERENCES HO_KHAU(MaHo),
    FOREIGN KEY (MaKhoanPhi) REFERENCES KHOAN_PHI(MaKhoanPhi)
);

CREATE TABLE PHUONG_TIEN (
    MaPhuongTien INT AUTO_INCREMENT PRIMARY KEY,
    MaHo INT NOT NULL,
    BienSo VARCHAR(50) NOT NULL,
    LoaiXe INT NOT NULL COMMENT '1: Oto, 2: XeMay/XeDap',
    TrangThai INT DEFAULT 1 COMMENT '1: Dang gui, 0: Da huy',

    FOREIGN KEY (MaHo) REFERENCES HO_KHAU(MaHo)
)

DELIMITER $$
CREATE TRIGGER AfterInsertHoKhau AFTER INSERT ON HO_KHAU
FOR EACH ROW
BEGIN
    UPDATE CAN_HO SET TrangThai = 1 WHERE SoCanHo = NEW.SoCanHo;
END$$

CREATE TRIGGER AfterSoftDeleteHoKhau AFTER UPDATE ON HO_KHAU
FOR EACH ROW
BEGIN
    IF NEW.IsDeleted = 1 AND OLD.IsDeleted = 0 THEN
        UPDATE CAN_HO SET TrangThai = 0 WHERE SoCanHo = NEW.SoCanHo;
    END IF;
END$$
DELIMITER ; 